{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aptueno.github",
    "module": "mavenjarpackagetest",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0.jar",
          "url": "mavenjarpackagetest-0.11.0.jar",
          "size": 3319,
          "sha512": "6c713c35d1362192062da0c933c12c534a92aa010506b60979bf6d09841afc7178faa81e0ce159bac3a3a8cd594bacf6f23f22ac3c7f351d4b8022a6eea14217",
          "sha256": "d35a81a997fe41b5ab481dceb95e051ce274e68ee57f8442d13c715714307cb0",
          "sha1": "dc02ffcd344a72576aaff2426e3655c526558b44",
          "md5": "064046be3023e31336a21d2fa527b7d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0.jar",
          "url": "mavenjarpackagetest-0.11.0.jar",
          "size": 3319,
          "sha512": "6c713c35d1362192062da0c933c12c534a92aa010506b60979bf6d09841afc7178faa81e0ce159bac3a3a8cd594bacf6f23f22ac3c7f351d4b8022a6eea14217",
          "sha256": "d35a81a997fe41b5ab481dceb95e051ce274e68ee57f8442d13c715714307cb0",
          "sha1": "dc02ffcd344a72576aaff2426e3655c526558b44",
          "md5": "064046be3023e31336a21d2fa527b7d6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0-javadoc.jar",
          "url": "mavenjarpackagetest-0.11.0-javadoc.jar",
          "size": 261,
          "sha512": "0577e7872878ecbc0474078a39a2ed3f5846f64c3ae3b7940006483a46a97db76af24cc28680a11fb01983308156544366f31e94884e2987f3091af9058002d8",
          "sha256": "7003f13ba61b90a4c5679909d4e95395e84dce6c80bc7976f7170fbcc2995aa5",
          "sha1": "8a5d69cc17fed960cba2c901c0548b50cf1754b6",
          "md5": "e3fc75deb140409bb7deadc2536d810a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0-sources.jar",
          "url": "mavenjarpackagetest-0.11.0-sources.jar",
          "size": 957,
          "sha512": "10349dee36de5a8312814b3c85954b9084acbfacbc4ee648c270d6a35a2f608d44ea13dfd84fd9a9cc674141834553fb3ef7fc01153e4a34d6b7fa9b2e3d2547",
          "sha256": "6dcfbe6e09504c1d3d92fbcf3bb6d03233ea6b40d0237af7361e6d243a84d7b1",
          "sha1": "c652e8c252fba31da2334dc11baf70a807cbc43a",
          "md5": "08e7f5e0842796315fea465bd1add538"
        }
      ]
    }
  ]
}
