{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.aptueno.github",
    "module": "mavenjarpackagetest",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0.jar",
          "url": "mavenjarpackagetest-0.11.0.jar",
          "size": 2985,
          "sha512": "264f7eb56d9cd94b4a3de196f52650ab32cc0dedefd9db1baac9fce4687d877f01051c653fef6ad69f56b013bdbefc8ab32708cdac090217af689162192bbede",
          "sha256": "6647a5ff2c24d30c9be889a52f0840d9cdc7704f73286952d8a6977416d49b90",
          "sha1": "dcb9b3661a0312779bf1c38c7071614fcab890e7",
          "md5": "7780832014a1470b16ba624fba5fd3a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0.jar",
          "url": "mavenjarpackagetest-0.11.0.jar",
          "size": 2985,
          "sha512": "264f7eb56d9cd94b4a3de196f52650ab32cc0dedefd9db1baac9fce4687d877f01051c653fef6ad69f56b013bdbefc8ab32708cdac090217af689162192bbede",
          "sha256": "6647a5ff2c24d30c9be889a52f0840d9cdc7704f73286952d8a6977416d49b90",
          "sha1": "dcb9b3661a0312779bf1c38c7071614fcab890e7",
          "md5": "7780832014a1470b16ba624fba5fd3a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0-javadoc.jar",
          "url": "mavenjarpackagetest-0.11.0-javadoc.jar",
          "size": 261,
          "sha512": "0577e7872878ecbc0474078a39a2ed3f5846f64c3ae3b7940006483a46a97db76af24cc28680a11fb01983308156544366f31e94884e2987f3091af9058002d8",
          "sha256": "7003f13ba61b90a4c5679909d4e95395e84dce6c80bc7976f7170fbcc2995aa5",
          "sha1": "8a5d69cc17fed960cba2c901c0548b50cf1754b6",
          "md5": "e3fc75deb140409bb7deadc2536d810a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mavenjarpackagetest-0.11.0-sources.jar",
          "url": "mavenjarpackagetest-0.11.0-sources.jar",
          "size": 951,
          "sha512": "7fa8c55c37c34795de6103da997eddedbaf25b66face2dede469860c4b0fde547f51fff61a9e7ebc759355151072d86cf49ffdc884b5d8ffff727160354844ad",
          "sha256": "22490939feea4e9ec82f4abc1d0c67917f3ebd577cc12c7783c6435974790672",
          "sha1": "b228b7bb1b10e5cdfae4b67d366e71f4d7669ea2",
          "md5": "ea5378d45bd45d27fc2c69dbc25db0ad"
        }
      ]
    }
  ]
}
