{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aptpod",
    "module": "mavenpackagetest",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenpackagetest-0.11.0.aar",
          "url": "mavenpackagetest-0.11.0.aar",
          "size": 3027,
          "sha512": "f21bd9aab30f8869c45f24e279b61925bfc902981d161956ec6f46781f65ee5fa37ffe2168752f9e0052f4ae9959986649f26ea735ad43080b2dd3412f0888ba",
          "sha256": "77d735eb92ff63ebab9e0269e4548bf09c5f5ee71ce02883f9b17183ded4a765",
          "sha1": "a79690fc58fdead022f032850256ad2d59a4571d",
          "md5": "238b24b72f285fc8775a0d4c70be8151"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenpackagetest-0.11.0.aar",
          "url": "mavenpackagetest-0.11.0.aar",
          "size": 3027,
          "sha512": "f21bd9aab30f8869c45f24e279b61925bfc902981d161956ec6f46781f65ee5fa37ffe2168752f9e0052f4ae9959986649f26ea735ad43080b2dd3412f0888ba",
          "sha256": "77d735eb92ff63ebab9e0269e4548bf09c5f5ee71ce02883f9b17183ded4a765",
          "sha1": "a79690fc58fdead022f032850256ad2d59a4571d",
          "md5": "238b24b72f285fc8775a0d4c70be8151"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mavenpackagetest-0.11.0-sources.jar",
          "url": "mavenpackagetest-0.11.0-sources.jar",
          "size": 1301,
          "sha512": "af5b1edd6032c5ac19d58255f39a9fda7239b3e98d9e8654244d80d76fefdde91eefa51d2136c14e4e8205d8daeaf9496cd86f12b87f20f1c4a1c11578e8ac03",
          "sha256": "f664b5fec9bd67781ea3092912dbbb72b6dc2278b92f8b6c740c3dab3aaa8255",
          "sha1": "476446c768015bd69cead9d8f41d70bab2d9a691",
          "md5": "0bf7bcf59c203548eb03acabbb0bf974"
        }
      ]
    }
  ]
}
