{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aptpod.github",
    "module": "mavenpackagetest",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenpackagetest-0.11.0.aar",
          "url": "mavenpackagetest-0.11.0.aar",
          "size": 3095,
          "sha512": "8527c32205f37057518023d8ba95a404a9f6f45c5dfc6275349d3ed7f6bdf6ef195e6b97c07099938898ad7f3116beab25148d059747dda971f179fccc95e933",
          "sha256": "2eeca202958b9f805b22800c56c7c1fdbe334d47403d1cf45b61fa3bd4cf0c2c",
          "sha1": "f090bd4bf29a78c8edb78d14f5a00b7fff9b5d47",
          "md5": "7161f3e3360a4818f3b7a95c6bcdb7a6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.23.3"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "mavenpackagetest-0.11.0.aar",
          "url": "mavenpackagetest-0.11.0.aar",
          "size": 3095,
          "sha512": "8527c32205f37057518023d8ba95a404a9f6f45c5dfc6275349d3ed7f6bdf6ef195e6b97c07099938898ad7f3116beab25148d059747dda971f179fccc95e933",
          "sha256": "2eeca202958b9f805b22800c56c7c1fdbe334d47403d1cf45b61fa3bd4cf0c2c",
          "sha1": "f090bd4bf29a78c8edb78d14f5a00b7fff9b5d47",
          "md5": "7161f3e3360a4818f3b7a95c6bcdb7a6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mavenpackagetest-0.11.0-sources.jar",
          "url": "mavenpackagetest-0.11.0-sources.jar",
          "size": 1431,
          "sha512": "8e009d3d9bed0f91da602a30bae46d2a23edbda0b26d03bbd1e1d6a624b5fafb81824849fa84f16a7ae8d47b0070bc76becdcd8b703ba5174a355f90d5e00e6d",
          "sha256": "71f54e6d8226d3608c49968c9f12dbbecc9e8331269b14de2783ac14aee6b20d",
          "sha1": "cdb8c32436e2a1f6891fc52e4f1be48abd250f33",
          "md5": "ef571bfa29bfa0c062d268c07c05694e"
        }
      ]
    }
  ]
}
